//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace BitacoraIp.Models
{
    public partial class bdd_bitacora_ipEntities : DbContext
    {
        public bdd_bitacora_ipEntities()
            : base("name=bdd_bitacora_ipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_bit_cat_area> tb_bit_cat_area { get; set; }
        public DbSet<tb_bit_cat_dga> tb_bit_cat_dga { get; set; }
        public DbSet<tb_bit_cat_empresa> tb_bit_cat_empresa { get; set; }
        public DbSet<tb_bit_cat_equipo_computo_marca> tb_bit_cat_equipo_computo_marca { get; set; }
        public DbSet<tb_bit_cat_equipo_telefono_modelo> tb_bit_cat_equipo_telefono_modelo { get; set; }
        public DbSet<tb_bit_cat_piso> tb_bit_cat_piso { get; set; }
        public DbSet<tb_bit_cat_regional> tb_bit_cat_regional { get; set; }
        public DbSet<tb_bit_cat_switch> tb_bit_cat_switch { get; set; }
        public DbSet<tb_bit_cat_tipo_equipo> tb_bit_cat_tipo_equipo { get; set; }
        public DbSet<tb_bit_cat_wireless> tb_bit_cat_wireless { get; set; }
        public DbSet<tb_bit_ip> tb_bit_ip { get; set; }
        public DbSet<tb_bit_ip_historico> tb_bit_ip_historico { get; set; }
        public DbSet<tb_bit_usuario> tb_bit_usuario { get; set; }
        public DbSet<tb_bit_usuario_historico> tb_bit_usuario_historico { get; set; }
        public DbSet<tb_bt_cat_equipo_computo_modelo> tb_bt_cat_equipo_computo_modelo { get; set; }
    }
}
