//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BitacoraIp.Models
{
    public partial class tb_bit_usuario_historico
    {
        public int pk_id { get; set; }
        public System.DateTime fecha_cambio { get; set; }
        public int cve_usuario { get; set; }
        public string nom_user_name { get; set; }
        public string nom_usuario { get; set; }
        public string ape_paterno { get; set; }
        public string ape_materno { get; set; }
        public int fk_cve_dga { get; set; }
        public int fk_cve_area { get; set; }
        public int fk_cve_empresa { get; set; }
        public int fk_cve_piso { get; set; }
        public int fk_cve_regional { get; set; }
        public string des_observacion { get; set; }
        public System.DateTime fec_alta { get; set; }
        public Nullable<System.DateTime> fec_baja { get; set; }
        public Nullable<System.DateTime> fec_actualiza { get; set; }
    
        public virtual tb_bit_cat_area tb_bit_cat_area { get; set; }
        public virtual tb_bit_cat_dga tb_bit_cat_dga { get; set; }
        public virtual tb_bit_cat_empresa tb_bit_cat_empresa { get; set; }
        public virtual tb_bit_cat_piso tb_bit_cat_piso { get; set; }
        public virtual tb_bit_cat_regional tb_bit_cat_regional { get; set; }
    }
    
}
